source 'https://rubygems.org'

gem "rails", "2.3.4"
gem "amatch", "0.2.3"
gem "amazon-ec2", "0.2.13"
gem "aws-s3", "0.5.1"
gem "builder", "2.1.2"
gem "capistrano"
gem "capistrano-ext"
gem "cgi_multipart_eof_fix", "2.5.0"
gem "daemons", "1.0.10"
gem "fastthread", "1.0.1"
gem "gem_plugin", "0.2.3"
gem "haml", "2.0.6"
gem "highline", "1.5.2"
gem "hoe", "1.8.2"
gem "hpricot", "0.6"
gem "htmlentities", "4.0.0"
gem "image_science", "1.1.3"
gem "mechanize", "0.9.2"
gem "mime-types", "1.15"
gem "mislav-will_paginate"
gem "mocha", "0.9.0"
gem "mongrel", "1.1.5"
gem "mongrel_cluster", "1.0.5"
gem "mysql", "2.7"
gem "net-scp", "1.0.2"
gem "net-sftp", "2.0.4"
gem "net-ssh", "2.0.20"
gem "net-ssh-gateway", "1.0.1"
gem "nokogiri", "1.2.3"
gem "passenger", "2.2.3"
gem "rack", "1.0.0"
gem "rake"
gem "rcov"
gem "RedCloth", "4.2.0"
gem "rspec", "1.1.4"
gem "rubyforge", "1.0.1"
gem "RubyInline", "3.6.7"
gem "rubyzip", "0.9.1"
gem "sources"
gem "spork"
gem "SQS"
gem "syntax"
gem "test-spec"
gem "xml-simple"
gem "ya2yaml"
gem "ZenTest"
gem "rubygems-update", "1.4.2"
gem "ruby-debug"
gem "json", "~> 1.8.2"
gem "spreadsheet"
gem "google-spreadsheet-ruby"
gem "roo", "1.9.3"
